name: eslint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  eslint: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: started lint
        run: npm run lint
      - name: started prettier
        run: npm run format   